[package]
name = "zing"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
cpal = "0.13.4"
ringbuf = "0.2.6"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
