[package]
name = "zing"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
cpal = "0.13.4"
eframe = { version = "0.18.0", features = ["dark-light"] }
ringbuf = "0.2.8"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
